import 'package:get/get.dart';

class WordLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'sign': 'Sign in to Account',
          'phone_number': 'Mobile Number',
          'password': 'Password',
          'forget_password': 'Forget Password',
          'sign_in': 'Sign in',
          'sign_up': 'Sign up',
          'have_not_account': "Don't have an account? ",
          'sign_in_google': 'Sign in with Google',
          'login_success': 'Login success',
          'login_failed': 'Login failed',
          'home_express1': 'Cheap car rental',
          'home_express2': 'Enjoy driving pleasure',
          'search': 'Search',
          'best_brand': 'The best brands',
          'day': 'Day',
          'overview': 'Overview',
          'see_more': 'See more',
          'see_less': 'See less',
          'seats': 'Seats',
          'reserve': 'Reserve',
          'available': 'Available',
          'reserve_now': 'Reserve Now',
          'brand': 'Brand',
          'car': 'Car',
          'search_cars': 'Search Cars',
          'reservation': 'Reservations',
          'reserve_at': "Reserve",
          'rent_now': 'Rent',
          'to_free': 'Free',
          'sign_up_to_customer': "Create a Customer account",
          'identity_file': 'Identity document',
          'profile_tof': "Profile photo",
          'add_identity_file': "Add your ID card or your passport",
          'add_profile_tof': "Add your profile photo",
          'no_image': "No image",
          'submit': "Submit",
          'settings': 'Settings',
          'account': 'Account',
          'account_description': 'Log out, Edit account',
          'app_language': 'App Language',
          'app_language_description': "Change the app language",
          'dark_mode': "Dark mode",
          'dark_mode_description': "Change on darkMode"
        },
        'fr_FR': {
          'sign': 'Connectez-vous à votre compte',
          'phone_number': 'Numéro de téléphone',
          'password': 'Mot de passe',
          'forget_password': 'Mot de passe oublié',
          'sign_in': 'Se connecter',
          'sign_up': "S'inscrire",
          'have_not_account': "Vous n'avez pas un compte? ",
          'sign_in_google': 'Se connecter avec Google',
          'login_success': 'Authentification réussie',
          'login_failed': 'Authentification échouée',
          'home_express1': 'Location de voiture à bon prix',
          'home_express2': 'Profitez du plaisir de conduire',
          'search': 'Rechercher',
          'best_brand': 'Les meilleures marques',
          'day': 'Jour',
          'overview': 'Aperçu',
          'see_more': 'voir plus',
          'see_less': 'voir moins',
          'seats': 'Places',
          'reserve': 'Réservé',
          'available': 'Disponible',
          'reserve_now': 'Réserver Maintenant',
          'brand': 'Marque',
          'car': 'Car',
          'search_cars': 'Rechercher des Voitures',
          'reservation': 'Réservations',
          'reserve_at': 'Réservée le',
          'rent_now': "Louer maintenant",
          'to_free': 'Libérer',
          'sign_up_to_customer': "Créer un compte client",
          'identity_file': "Document d'identité",
          'profile_tof': "Photo de profile",
          'add_identity_file':
              "Ajoutez votre carte d'identité ou votre passport",
          'add_profile_tof': "Ajoutez votre photo de profile",
          'no_image': "Aucune image",
          'submit': "Soumettre",
          'settings': 'Parametre',
          'account': 'Compte',
          'account_description':
              'Se déconnecter, Changer les informations de son compte',
          'app_language': 'Langues',
          'app_language_description': "Changer la langue de l'application",
          'dark_mode': "Mode foncée",
          'dark_mode_description': "Changer en  mode foncée"
        }
      };
}
