import 'package:get/get.dart';

class WordLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'sign': 'Sign in to Account',
          'sign_up_label': "Create an account",
          'phone_number': 'Mobile Number',
          'password': 'Password',
          'email': 'Email',
          'fullName': "FullName",
          'forget_password': 'Forget Password',
          'sign_in': 'Sign in',
          'sign_up': 'Sign up',
          'sign_up_ok': "Account created successfully",
          'have_not_account': "Don't have an account? ",
          'sign_in_google': 'Sign in with Google',
          'login_success': 'Login success',
          'login_failed': 'Login failed',
          'home_express1': 'Cheap car rental',
          'home_express2': 'Enjoy driving pleasure',
          'searchpage': 'Search',
          'best_brand': 'The best brands',
          'day': 'Day',
          'overview': 'Overview',
          'see_more': 'See more',
          'see_less': 'See less',
          'seats': 'Seats',
          'reserve': 'Reserve',
          'available': 'Available',
          'reserve_now': 'Reserve Now',
          'brand': 'Brand',
          'car': 'Car',
          'search_cars': 'Search Cars',
          'reservation': 'Reservations',
          'reserve_at': "Reserve",
          'rent_now': 'Rent Now',
          'to_free': 'Free',
          'sign_up_to_customer': "Create a Customer account",
          'identity_file': 'Identity document',
          'profile_tof': "Profile photo",
          'add_identity_file': "Add your ID card or your passport",
          'add_profile_tof': "Add your profile photo",
          'no_image': "No image",
          'submit': "Submit",
          'settings': 'Settings',
          'account': 'Account',
          'account_description': 'Log out, Edit account',
          'app_language': 'App Language',
          'app_language_description': "Change the app language",
          'dark_mode': "Dark mode",
          'dark_mode_description': "Change on darkMode",
          'field_must_be_filled': "This field must be filled",
          'enter_valid_mail': "Please enter a valide email",
          'weak_password': "The password is weak",
          'email_already_in_use':
              "An account already exists for this email address",
          'failed': "Failed",
          'succeeded': "Succeeded",
          'network_request_failed':
              "Impossible to connect. Please check your internet connection",
          'user_not_found': "No user found for this email",
          'wrong_password': "Incorrect password for this user",
          'need_identity_file': "You need to add an identity file",
          'need_profile_image': "You need to add an profile image",
          'is_time_out_exception': "The operation take a long time",
          'is_socketException': "The connection has been interrupted",
          'is_firebase_exception': "Processing error",
          'is_platform_exception': "Platform error",
          'no_car_rented': "You have rented no car yet",
          'profile': "Profile",
          'cancel': "Cancel",
          'edit': 'Edit',
          'update_ok': "Modification made",
          'french': "French",
          'english': "English",
          'language': "Language",
          'you_are_customer': "You are now a customer",
          'nbr_rent_day': "Number of rental days",
          'total': "Total",
          'pay': "Pay",
          'log_out': "Log out"
        },
        'fr_FR': {
          'sign': 'Connectez-vous à votre compte',
          'sign_up_label': "Créer un compte",
          'phone_number': 'Numéro de téléphone',
          'email': 'Email',
          'fullName': "Nom Complet",
          'password': 'Mot de passe',
          'forget_password': 'Mot de passe oublié',
          'sign_in': 'Se connecter',
          'sign_up': "S'inscrire",
          'sign_up_ok': "Compte créé avec succès",
          'have_not_account': "Vous n'avez pas un compte? ",
          'sign_in_google': 'Se connecter avec Google',
          'login_success': 'Authentification réussie',
          'login_failed': 'Authentification échouée',
          'home_express1': 'Location de voiture à bon prix',
          'home_express2': 'Profitez du plaisir de conduire',
          'searchpage': 'Rechercher',
          'best_brand': 'Les meilleures marques',
          'day': 'Jour',
          'overview': 'Aperçu',
          'see_more': 'voir plus',
          'see_less': 'voir moins',
          'seats': 'Places',
          'reserve': 'Réservé',
          'available': 'Disponible',
          'reserve_now': 'Réserver Maintenant',
          'brand': 'Marque',
          'car': 'Car',
          'search_cars': 'Rechercher des Voitures',
          'reservation': 'Réservations',
          'reserve_at': 'Réservée le',
          'rent_now': "Louer maintenant",
          'to_free': 'Libérer',
          'sign_up_to_customer': "Créer un compte client",
          'identity_file': "Document d'identité",
          'profile_tof': "Photo de profile",
          'add_identity_file':
              "Ajoutez votre carte d'identité ou votre passport",
          'add_profile_tof': "Ajoutez votre photo de profile",
          'no_image': "Aucune image",
          'submit': "Soumettre",
          'settings': 'Parametre',
          'account': 'Compte',
          'account_description':
              'Se déconnecter, Changer les informations de son compte',
          'app_language': 'Langues',
          'app_language_description': "Changer la langue de l'application",
          'dark_mode': "Mode foncée",
          'dark_mode_description': "Changer en  mode foncée",
          'field_must_be_filled': "Ce champs doit être rempli",
          'enter_valid_mail': "Veuillez mettre un email valide",
          'weak_password': "Le mot de pass est faible",
          'email_already_in_use':
              "Un compte existe déjà pour cette adresse e-mail",
          'failed': "Échoué",
          'succeeded': "Réussi",
          'network_request_failed':
              "Impossible de se connecter. Veuillez vérifier votre connexion Internet",
          'user_not_found': "Aucun utilisateur trouvé pour cet e-mail",
          'wrong_password': "Mot de passe incorrect pour cet utilisateur",
          'need_identity_file': "Vous devez ajouter un fichier d'identité",
          'need_profile_image': "Vous devez ajouter une image de profile",
          'is_time_out_exception': "L'opération prend beaucoup de temps",
          'is_socketException': "Il y a eu interruption de la connexion",
          'is_firebase_exception': "Erreur de traitement",
          'is_platform_exception': "Erreur de plateforme",
          'no_car_rented': "Vous avez loué aucune voiture pour le moment",
          'profile': "Profile",
          'cancel': "Annuler",
          'edit': 'Modifier',
          'update_ok': "Modification faite",
          'french': "Français",
          'english': "Anglais",
          'language': "Language",
          'you_are_customer': "Vous êtes maintenant un client",
          'nbr_rent_day': " Nombre de jour de location",
          'total': "Total",
          'pay': "Payer",
          'log_out': "Se déconnecter"
        }
      };
}
